openapi: 3.0.2
info:
  title: Redis-REST with Referencing for Chemical Normalization
  description: 'Redis-REST with Referencing for Chemical Normalization'
  version: '1.0.0'
  contact:
    email: powen@renci.org
  termsOfService: http://robokop.renci.org:7055/tos?service_long=Redis-REST+with+Referencing&provider_long=the+Translator+Consortium
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: Interfaces(s)
paths:
  /get:
    get:
      tags:
        - redis
      summary: 'Get value(s) for key(s)'
      description: ''
      parameters:
        - in: query
          name: key
          schema:
            type: array
            items:
              type: string
            example:
              -  CHEBI:77287
      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: object
                example:
                  request: response