openapi: 3.0.2
info:
  title: Redis-REST with Referencing
  description: 'A REST interface for a Redis database, with referencing'
  version: '1.0.0'
  contact:
    email: patrick@covar.com
  termsOfService: http://robokop.renci.org:7055/tos?service_long=Redis-REST+with+Referencing&provider_long=the+Translator+Consortium
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: redis
paths:
  /get:
    get:
      tags:
        - redis
      summary: 'Get value(s) for key(s)'
      description: ''
      parameters:
        - in: query
          name: key
          schema:
            type: array
            items:
              type: string
            example:
              - "GO:0032157"
              - "UMLS:C0856524"

      responses:
        '200':
          description: Results
          content:
            application/json:
              schema:
                type: object
                example:
                  GO:0032157:
                    id:
                      identifier: "GO:0032157"
                      label: "prospore contractile ring"
                    equivalent_identifiers:
                      - identifier: "GO:0032157"
                        label: "prospore contractile ring"
                    type:
                      - "cellular_component"
                      - "named_thing"
                      - "biological_entity"
                      - "organismal_entity"
                      - "anatomical_entity"

                  UMLS:C0856524:
                   id:
                    identifier: "UMLS:C0856524"
                  equivalent_identifiers:
                   - identifier: "UMLS:C0856524"
                   - identifier: "MEDDRA:10035322"
                  type:
                  - "phenotypic_feature"
                  - "named_thing"
                  - "biological_entity"
                  - "disease_or_phenotypic_feature"

