apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-normalization-r3-redis-deployment
  labels:
    service: node-normalization-r3-redis
    app: node-normalization-r3-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-normalization-r3-redis
  template:
    metadata:
      labels:
        app: node-normalization-r3-redis
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: node-normalization-r3-redis
        image: redis
        ports:
          - containerPort: 6379
            name: redis-port
        resources:
          requests:
            memory: "62Gi"
        volumeMounts:
          - mountPath: /data
            name: node-normalization-redis-data-mount
          - mountPath: /etc/sysctl.conf
            name: sysctlconfig
            subPath: vmovercommit
      restartPolicy: Always
      volumes:
        - name: node-normalization-redis-data-mount
          persistentVolumeClaim:
            claimName: node-normalization-pvc
        - name: sysctlconfig
          configMap:
            name: sysctl-configmap
            defaultMode: 0555
