apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: node-normalization-pv
  spec:
    accessModes:
      - ReadWriteOnce
    capacity:
      storage: 100Gi
    # nfs:
    #   path: 
    #   server: 
    persistentVolumeReclaimPolicy: Retain
    storageClassName: node-normalization-pv

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: node-normalization-pvc
    labels:
      type: local
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
    storageClassName: node-normalization-pv
